### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by msimonc** [barrystaes/react-trebuchet#16] opened 2016-11-28 02:38 UTC
on `npm start`:
```
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.10.8.69:3001
 -----------------------------------
[BS] Serving files from: src
[BS] Watching files...
webpack built a981b6e6af8b451f975d in 1212ms
Hash: a981b6e6af8b451f975d
Version: webpack 1.12.13
Time: 1212ms
    Asset     Size  Chunks       Chunk Names
bundle.js  46.9 kB       0       main
chunk    {0} bundle.js (main) 8.29 kB [rendered]
    [0] multi main 40 bytes {0} [built] [1 error]
    [1] ./~/ansi-regex/index.js 135 bytes {0} [built]
    [2] ./~/strip-ansi/index.js 161 bytes {0} [built]
    [3] (webpack)-hot-middleware/client-overlay.js 1.01 kB {0} [built]
    [4] (webpack)-hot-middleware/client.js 3.43 kB {0} [built]
    [5] (webpack)-hot-middleware/process-update.js 3.27 kB {0} [built]
    [6] (webpack)/buildin/module.js 251 bytes {0} [built]

ERROR in ./src/index.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /ProjectSamples/REDUX/react-trebuchet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:36
    at /ProjectSamples/REDUX/react-trebuchet/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:22
    at Array.map (native)
```

**Comment by barrystaes** [comment] 2019-07-29 14:09
No longer relevant, closing now since repository is being archived.

This problem was not reproduced or fixed that i know of. If you still want to fix this, fork this repo and create a new issue there.

**Closed as completed by barrystaes** 2019-07-29 14:09 UTC
